
CREATE TABLE MEMBER_WITH_AUTHORITY
(
  MEMBER_SEQ    VARCHAR(50) NULL     COMMENT '회원 시퀀스',
  MEMBER_ID     VARCHAR(50) NULL     COMMENT '회원 ID',
  PASSWORD      VARCHAR(500) NULL     COMMENT '암호',
  NAME          VARCHAR(50) NULL     COMMENT '회원이름',
  EMAIL         VARCHAR(50) NULL     COMMENT '이메일',
  CELLPHONE     VARCHAR(50) NULL     COMMENT '손전화',
  AUTHORITY     VARCHAR(50) NULL     COMMENT '권한',
  REGISTER_SEQ  VARCHAR(50) NULL     COMMENT '작성자 ID',
  REGISTRY_DATE TIMESTAMP   NULL     COMMENT '작성일짜',
  MODIFIER_SEQ  VARCHAR(50) NULL     COMMENT '변경자 ID',
  MODIFY_DATE   TIMESTAMP   NULL     COMMENT '변경일짜'
) COMMENT '회원정보와권한';
