
CREATE TABLE CAR_INFORS
(
  CAR_NAME     VARCHAR(50) NOT NULL COMMENT '자동차이름',
  YEAR         VARCHAR(50) NOT NULL COMMENT '연식',
  CAR_INFOR_ID VARCHAR(50) NOT NULL,
  COMPANY_ID   VARCHAR(50) NOT NULL,
  PRIMARY KEY (CAR_INFOR_ID)
) COMMENT '차_정보';

CREATE TABLE FACTORYS
(
  COMPANY_ID VARCHAR(50) NOT NULL,
  COMPANY    VARCHAR(50) NOT NULL COMMENT '회사명',
  PRIMARY KEY (COMPANY_ID)
) COMMENT '자동차회사';

CREATE TABLE OPTION_INFORS
(
  OPTION_INFOR_ID VARCHAR(50)  NOT NULL,
  OPTION_NAME     VARCHAR(500) NOT NULL COMMENT '옵션명',
  PRIMARY KEY (OPTION_INFOR_ID)
) COMMENT '옵션 정보';

CREATE TABLE OPTIONS
(
  OPTION_ID       VARCHAR(50) NOT NULL,
  CAR_INFOR_ID    VARCHAR(50) NOT NULL,
  OPTION_INFOR_ID VARCHAR(50) NOT NULL,
  PRIMARY KEY (OPTION_ID)
);

ALTER TABLE CAR_INFORS
  ADD CONSTRAINT FK_FACTORYS_TO_CAR_INFORS
    FOREIGN KEY (COMPANY_ID)
    REFERENCES FACTORYS (COMPANY_ID);

ALTER TABLE OPTIONS
  ADD CONSTRAINT FK_CAR_INFORS_TO_OPTIONS
    FOREIGN KEY (CAR_INFOR_ID)
    REFERENCES CAR_INFORS (CAR_INFOR_ID);

ALTER TABLE OPTIONS
  ADD CONSTRAINT FK_OPTION_INFORS_TO_OPTIONS
    FOREIGN KEY (OPTION_INFOR_ID)
    REFERENCES OPTION_INFORS (OPTION_INFOR_ID);
